site_name: apilyzer - Analisador de API
repo_url: https://github.com/Tchez/apilyzer
repo_name: tchez/apilyzer
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
- mkdocstrings:
    handlers:
      python: 
        paths: [apilyzer]