[tool.poetry]
name = "apilizer"
version = "0.1.0"
description = ""
authors = ["Marco Antônio <marcomartins06@rede.ulbra.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
